default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 123456 
  pool: 5

development:
  <<: *default
  database: kakia_sports_store_development

test:
  <<: *default
  database: kakia_sports_store_test

production:
  <<: *default
  database: kakia_sports_store_production
